
services:
  mysql:
    image: mysql:8.0
    container_name: unifecaf_mysql_compose
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: unifecaf_flix
      MYSQL_USER: unifecaf
      MYSQL_PASSWORD: senha123
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  

volumes:
  mysql_data:
